#!/bin/sh

echo "============ Tests started ===========\n" | tee report

error_code=0

for f in `ls test*.py`
do
	echo "-----> $f" | tee -a report
	output=`python2 $f`

	if [ $? = 0 ]
	then
		echo | tee -a report
		echo Test [$f] passed | tee -a report	
	else
		error_code=1	
	fi

	echo $output | tee -a report

	echo | tee -a report
done

echo "============ Tests ended =============" | tee -a report
exit $error_code
