#!/bin/sh

export NODE_ENV=production

id=`id | cut -f1 -d'('`

if [ $id != "uid=0" ]
then
	echo
	echo "===> Usage: sudo $0"
	echo
	exit
fi

while :
do
	/usr/local/bin/node https.js
	sleep 1
	echo "================> Restarting ===================="
done
