#!/bin/sh

syspatch
pkg_add postgresql-server postgresql-client node

rcctl enable postgresql
rcctl start postgresql

head /dev/random | sha256 > db.password
head /dev/random | sha256 > crl.db.password

auth_password=`cat db.password`
sed -i "s/XXXAUTHXXX/$auth_password/" postgres.sql 

crl_password=`cat crl.db.password`
sed -i "s/XXXCRLXXX/$crl_password/" postgres.sql 

cp db.password /var/postgresql
cp setup.postgres.openbsd /var/postgresql
chmod a+x /var/postgresql/setup.postgres.openbsd /var/postgresql

cp postgres.sql /var/postgresql
su _postgres -c /var/postgresql/setup.postgres.openbsd

# setup postgres

cp rc.local /etc/
cp pf.conf /etc/

openssl req -x509 -nodes -days 365 -subj "/CN=localhost" -newkey rsa:2048 -keyout key.pem -out server.pem

git clone https://github.com/rbccps-iisc/node-aperture
cd node-aperture
npm install

cd ..
npm install
npm audit fix

echo syspatch >> /etc/daily.local
echo boot >> /etc/boot.conf

echo "Press enter to reboot. Ctrl + C to quit"
read

reboot
