@startuml
hide footbox

autonumber "<b>[0]"

actor "Consumer" as c

participant "IUDX Auth server" as auth


c -[#green]> auth : HTTPS POST/iudx/1.0/audit/tokens\nhours: <audit-report-for-last-n-hours>

auth -[#green]> c : HTTP 200 OK\nbody=[{"token-issued-at":<time>, "expiry":<expiry>, "certificate-serial-number": <serial>, "certificate-fingerprint":<fingerprint>, "request":<request-in-json>}, ...]

@enduml

