@startuml
hide footbox

autonumber "<b>[0]"

participant "Resource server" as r

participant "IUDX Auth server" as auth


r -[#green]> auth : HTTPS POST/iudx/1.0/introspect\ntoken: <access-token>
alt Token is valid
    auth -[#green]> r : HTTP 200 OK\ncontent-type: application/json\nbody={active: true/false, username: <username>, expiry: <expiry-in-seconds>, request: <request-in-json>}

else Invalid token
    auth -[#green]> r : HTTP 403 Forbidden
end

@enduml
