@startuml
hide footbox

autonumber "<b>[0]"

actor "Consumer" as c

participant "IUDX Auth server" as auth


c -[#green]> auth : HTTPS POST/iudx/1.0/revoke\ntoken: <access-token>
alt Token is valid
    auth -[#green]> c : HTTP 200 OK
else Invalid token
    auth -[#green]> c : HTTP 400 Bad request
end

@enduml
